# Generated by Django 4.2.1 on 2023-11-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_tgadmin_alter_book_image_alter_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=88),
        ),
    ]
