# Generated by Django 4.1.7 on 2023-12-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name_en',
            field=models.CharField(help_text='Kitob nomini yozing', max_length=55, null=True, verbose_name='Kitob oti'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ru',
            field=models.CharField(help_text='Kitob nomini yozing', max_length=55, null=True, verbose_name='Kitob oti'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_uz',
            field=models.CharField(help_text='Kitob nomini yozing', max_length=55, null=True, verbose_name='Kitob oti'),
        ),
        migrations.AddField(
            model_name='book',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
