# Generated by Django 4.1.7 on 2023-12-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_cartproduct_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
